version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ROOM_1:1:1,ROOM_2:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-node-consumer:
    image: kafka-node-consumer
    ports:
      - "3001:3002"
  kafka-producer-api:
    image: kafka-producer-api
    ports:
      - "8080"
